export const DAILY_TIPS: readonly string[] = [
  "Read 10 pages today—small steps compound fast.",
  "Keep a notebook beside your book; jot one idea you can use.",
  "Try a 25-minute reading sprint, then a 5-minute break.",
  "Switch formats: audiobook on a walk, ebook at night, print in the morning.",
  "Highlight less, summarize more—one paragraph recap beats five highlights.",
  "Re-read your favorite chapter; depth > breadth.",
  "Set a daily reading goal and track your progress in a simple app.",
  "Join a book club to discuss and gain new perspectives on your reads.",
  "Read outside your comfort zone—pick a genre you've never tried.",
  "Create a cozy reading nook to make the habit more enjoyable.",
  "Pair reading with your favorite tea or coffee for a relaxing ritual.",
  "Use flashcards to remember key quotes or concepts from books.",
  "Read aloud to improve comprehension and retention.",
  "Challenge yourself to finish a book in a week—pace yourself daily.",
  "Explore book summaries first to decide if a full read is worth it.",
  "Rotate between fiction and non-fiction for balanced mental stimulation.",
  "Take notes on how a book changes your thinking or habits.",
  "Listen to podcasts about books to discover new recommendations.",
  "Set aside screen time for reading time—swap scrolling for pages.",
  "Revisit childhood favorites to spark joy and nostalgia.",
  "Experiment with speed reading techniques for lighter material.",
  "Discuss books with friends or online communities for deeper insights.",
  "Keep a reading journal: what you loved, hated, and learned.",
  "Try reading in a foreign language to build skills and vocabulary.",
  "Focus on one theme per month, like leadership or adventure.",
  "Use bookmarks with motivational quotes to inspire your sessions.",
  "Read before bed to unwind and improve sleep quality.",
  "Track books read this year—aim for a personal record.",
  "Explore poetry for quick, impactful daily reads.",
  "Pair books with related movies or documentaries for context.",
  "Practice active reading: question, predict, and connect ideas.",
  "Donate books you've finished to share the knowledge.",
  "Set reminders on your phone for daily reading breaks.",
  "Read short stories when time is limited—still counts!",
  "Reflect on how a book's lessons apply to your life today.",
  "Build a TBR (to-be-read) list and prioritize based on mood.",
  "Try mind mapping chapters to visualize connections.",
  "Read with a pen in hand—annotate for engagement.",
  "Explore audiobooks during commutes or chores.",
  "Challenge: Read a book from every continent this year.",
  "Join online reading challenges for motivation and fun.",
  "Re-read notes from past books to reinforce learning.",
  "Focus on quality over quantity—savor each page.",
  "Pair reading with exercise, like stationary bike sessions.",
  "Discover indie authors for fresh, unique voices.",
  "Use apps to gamify reading with streaks and rewards.",
  "Read biographies to learn from real-life successes.",
  "Take a day off screens and dedicate it to books.",
  "Experiment with different reading positions for comfort.",
  "Share book recommendations on social media.",
  "Set micro-goals: One chapter before lunch.",
  "Explore graphic novels for visual storytelling.",
  "Reflect weekly: What book impacted me most?",
  "Build a home library—organize by mood or color.",
  "Try tandem reading: Same book with a partner.",
  "Focus on mindfulness while reading—be present.",
  "Read essays for bite-sized wisdom.",
  "Track reading time to optimize your schedule.",
  "Discover classics you've skipped—start small.",
  "Use highlighters sparingly; opt for sticky notes.",
  "Pair books with music playlists for immersion.",
  "Challenge: No rereads this month—new books only.",
  "Journal: How does this book make me feel?",
  "Explore self-help books for personal growth tips.",
  "Read in nature—park or beach for fresh air.",
  "Set a page minimum before allowing distractions.",
  "Discover book series for ongoing adventures.",
  "Reflect on character development in your reads.",
  "Try digital detox days focused on print books.",
  "Share quotes from books to inspire others.",
  "Build reading stamina: Increase pages gradually.",
  "Explore memoirs for real, relatable stories.",
  "Use timers for focused, uninterrupted sessions.",
  "Reorganize your bookshelf for visual appeal.",
  "Read diverse authors for broader worldviews.",
  "Pair reading with journaling prompts.",
  "Challenge: Finish a trilogy in a month.",
  "Focus on plot twists—predict and reflect.",
  "Discover audiobooks with great narrators.",
  "Set reading rewards: Treat after milestones.",
  "Explore historical fiction for educational fun.",
  "Track genres read to ensure variety.",
  "Read with questions in mind for active engagement.",
  "Build a reading community—start a group chat.",
  "Try skimming non-essential parts wisely.",
  "Reflect daily: One takeaway from today's read.",
  "Discover free ebooks from libraries online.",
  "Pair books with related TED talks.",
  "Challenge: Read a book in one sitting.",
  "Focus on writing styles—note what works.",
  "Explore sci-fi for imaginative escapes.",
  "Use book apps for personalized suggestions.",
  "Re-read endings for deeper understanding.",
  "Share book hauls to build excitement.",
  "Build habits: Read after waking or before sleep.",
  "Discover thrillers for page-turning suspense.",
  "Track progress visually—charts or apps.",
  "Read poetry aloud for rhythmic enjoyment.",
  "Explore philosophy books for mind expansion.",
  "Set boundaries: No phone during reading.",
  "Reflect on themes across multiple books.",
  "Discover young adult fiction for quick reads.",
  "Pair reading with healthy snacks.",
  "Challenge: Diversify by author backgrounds.",
  "Focus on vocabulary—note new words.",
  "Explore cookbooks for practical inspiration.",
  "Use reading lamps for eye comfort.",
  "Build consistency: Same time every day.",
  "Share reviews to solidify thoughts.",
  "Discover fantasy worlds for creativity boost.",
  "Set a 'start line'—open the book and read the first sentence immediately.",
  "Stack habits: Read right after brushing your teeth.",
  "Try a morning paragraph—low friction beats big plans.",
  "Preview chapters: skim headings, then read deeply.",
  "Close the loop—finish the section you started yesterday.",
  "Use airplane mode to keep pages uninterrupted.",
  "Keep a 'quotes only' note to revisit sparks fast.",
  "Underline questions, not just answers.",
  "Switch chairs or locations when your focus dips.",
  "Timebox decisions: 2 minutes to pick what to read.",
  "Carry a pocket book for micro-moments.",
  "Keep DNF permission—abandon books guilt-free.",
  "Make a 'reread later' shelf for high-impact titles.",
  "Write a one-sentence summary per chapter.",
  "Try themed days: Monday memoir, Tuesday tech, etc.",
  "Log page ranges, not just totals.",
  "Do a 7-day reading streak reset every month.",
  "Pair a difficult book with an easy companion read.",
  "Ask: What’s the author’s core claim?",
  "Create a glossary for specialized topics.",
  "Use the Pomodoro bell as a 'bookmark' cue.",
  "Turn margins into a conversation—argue with the author.",
  "Ask three why’s for each big idea.",
  "Translate one key paragraph into your own words.",
  "Build a 'concept ladder'—what idea depends on what?",
  "Schedule a 15-minute Sunday review ritual.",
  "Keep book notes searchable—use clear tags.",
  "Swap doomscrolling for two pages at lunch.",
  "Summarize a chapter to a friend via voice memo.",
  "Give every book a 'use case' before starting.",
  "Test recall: close the book and write three bullets.",
  "Create a skimming code: ?, !, → for questions, insights, actions.",
  "Read with bookmarks that include prompts.",
  "Audit your shelves—donate one for every five you add.",
  "Pick a 'keystone' author and read adjacent thinkers.",
  "Do a quarterly 'top 5 ideas' compilation.",
  "Keep a 'didn’t work for me' log—avoid repeats.",
  "Track your attention—note when you drift and why.",
  "Read introductions last to test your understanding.",
  "Try a 'reverse outline' after dense chapters.",
  "Limit highlight count to five per chapter.",
  "Ask: What would change my mind here?",
  "Commit to the next page—focus on micro-progress.",
  "Use a stand or pillow for posture and stamina.",
  "Turn on grayscale to curb phone temptation.",
  "Read the acknowledgments to find new authors.",
  "Add a post-it for actionables per book.",
  "Rehearse definitions aloud to lock them in.",
  "Skim first, then hunt for the author’s evidence.",
  "Test teaching: explain a concept to a child.",
  "Keep a 'did this help me?' score in notes.",
  "Pair every insight with one experiment you’ll try.",
  "Sort your TBR by energy: heavy, medium, light.",
  "Create a 'reading rain' playlist—steady ambience.",
  "Use a physical timer on the desk for sprints.",
  "Write your reading pledge on the first page.",
  "Batch library holds to arrive in waves.",
  "Leave books face-up as visual cues.",
  "Ask: What’s the story behind this data?",
  "Use chapter endpoints as natural stop points.",
  "Make 'finish lines' visible—clip pages into segments.",
  "Set a weekly genre wildcard to stay curious.",
  "Turn quotes into wallpaper on your lock screen.",
  "Put your bookmark at tomorrow’s starting paragraph.",
  "Host a 15-minute micro-club at lunch weekly.",
  "Try 'parallel reading'—two books on one theme.",
  "Map characters when starting complex fiction.",
  "Create a reference index page in the back.",
  "Schedule 'library walks' to browse serendipitously.",
  "Ask: What’s the author not saying?",
  "Star one idea you’ll apply within 24 hours.",
  "Limit yourself to one open non-fiction at a time.",
  "Use page photos sparingly for diagrams you’ll revisit.",
  "Try hand-copying a paragraph you love.",
  "Set a 'no new books until two finished' rule.",
  "Read the last paragraph of a chapter first for framing.",
  "Do a 'ten pages before screens' morning rule.",
  "Keep a 'mood shelf' for quick choosing.",
  "Track abandon rate—optimize future picks.",
  "Annotate with verbs: define, compare, challenge, apply.",
  "Build a personal canon—5 books per domain.",
  "Use index hunting to jump to what you need now.",
  "Highlight contradictions and seek resolution.",
  "Write mini-reviews right after finishing.",
  "Create a 'book to practice' list, not just 'to read'.",
  "Do a monthly bookshelf reshuffle—freshness matters.",
  "Ask: If this is true, what changes?",
  "Keep a pen + sticky notes in every room.",
  "Designate 'slow books' for weekends only.",
  "Use a book seat/beanbag for hands-free reading.",
  "Try multilingual pair reading for language growth.",
  "Set a 'lights out but audiobook on' wind-down.",
  "Compare translations for classics—pick your voice.",
  "Make a 'sketch the idea' margin habit.",
  "Do a 24-hour sprint to finish near-done books.",
  "Track reading by energy blocks, not clock time.",
  "Build a 'reread calendar'—6 months, 2 years, 5 years.",
  "End sessions with one written question for tomorrow.",
  "Create an 'antidote shelf'—books that calm you.",
  "Let audiobooks replace background TV.",
  "Keep your current book visible in your bag front pocket.",
  "Bundle read + walk: pace while listening indoors.",
  "Audit your notes: find one habit to implement now.",
  "Join an author AMA or live Q&A for context.",
  "Use topic clusters: three slim books > one massive tome.",
  "Practice 'progressive summarization' over time.",
  "Switch to larger fonts at night for comfort.",
  "Keep a micro-bookmark for mid-page stops.",
  "Set a 'finish by' date on your calendar.",
  "Run a 30-day 'one idea per day' share challenge.",
  "Ask friends for 'one book that changed you' lists.",
  "Try reading with a ruler/guide to reduce regressions.",
  "Set 'no book buying' weeks—read what you own.",
  "Keep a DNF jar—celebrate smart exits.",
  "Audit screen brightness vs. eye strain after 20 min.",
  "Build a 'concept map' at book halfway point.",
  "Use a posture check timer every 15 minutes.",
  "Read the bibliography like a treasure map.",
  "Do a 'chapter title rewrite' to test comprehension.",
  "Practice subvocalization reduction on easy texts.",
  "Use page anchors: mark 25%, 50%, 75% progress goals.",
  "Ask: What metaphor is driving this argument?",
  "Contrast two opposing authors on the same topic.",
  "Keep a 'quotable characters' list for fiction.",
  "Try 'silent book club' sessions with friends.",
  "Create a ritual start: tea, lamp, pen, open.",
  "Note personal biases that affect your reading.",
  "Use a lap desk for couch reading ergonomics.",
  "Print your yearly reading log cover as wall art.",
  "Pair each book with a 'next action' task.",
  "Do a mid-book checkpoint: continue or quit?",
  "Make your TBR finite—cap at 25 active options.",
  "Ask librarians for 'if you liked this…' picks.",
  "Practice speed variances—slow down for arguments.",
  "Try bilingual editions to compare phrasing.",
  "Keep a 'scene that moved me' index for fiction.",
  "Mark craft techniques you admire in authors.",
  "Create a 'reading retreat' day quarterly.",
  "End with gratitude—note one joy from today’s pages.",
];
